### ISSUE TITLE
Plink path in system calls

### ISSUE THREAD

**Issue by RasmusBrostroem** [FireGutter/geneference#17]
We need to be more precise with what the user should input into the function regarding system calls.

An issue is the plink path, where it is stated that the user should input the path to PLINK, but in the input validation the check requires the user to give the path to the folder that the plink file is in.

**Comment by BigMag69** [comment]
we are going to change the documentation of the functions such that it is clear where the path should lead.
(the folder where plink.exe lies)
@jbirkesteen

**Comment by jbirkesteen** [comment]
_Note to self:_ This is changed on **spaces_and_plink** branch.
