### ISSUE TITLE
Corrections for plots

### ISSUE THREAD

**Issue by jbirkesteen** [FireGutter/geneference#23]
- [x] `plot_pmgl_vs_true`: References wrong load function
- [x] `plot_manhattan`: Change it such that it does not remove all points below 0.05-significance line
- [x] `plot_estimates_vs_true`: Make it clear that function needs PLINK output with estimates of beta _(for instance .qassoc_)
- [x] `plot_pval_qq`: Make dots smaller

**Comment by RasmusBrostroem** [comment]
plot_manhattan: Include legend for lines
