### ISSUE TITLE
Simulation functions can't overwrite

### ISSUE THREAD

**Issue by jbirkesteen** [FireGutter/geneference#24]
If the user runs a simulation in a directory where another simulation has been run, it appends the results of `beta.txt`, `MAFs.txt`, `genotypes.ped` and `phenotypes.txt` to the end of the existing files.

#### Possible approaches
- Check if files exist and warn user/stop function
- Make function delete existing file and then write the file again

**Comment by jbirkesteen** [comment]
Which approach do you think you'll go with, @Javert-ctrl?
@RasmusBrostroem had a few ideas.

**Comment by Javert-ctrl** [comment]
I have  now implemented a function where we allow the user to take different actions according to the information listed above :D. E.g. The user can over-write the data, stop the function or even create a new folder for the new data!

**Comment by jbirkesteen** [comment]
> I have now implemented a function where we allow the user to take different actions according to the information listed above :D. E.g. The user can over-write the data, stop the function or even create a new folder for the new data!

Great!! Let's look at it tomorrow morning - perhaps after the meeting with Emil?
