### ISSUE TITLE
Family_dist_simulation is spelled wrong

### ISSUE THREAD

**Issue by RasmusBrostroem** [FireGutter/geneference#29]
The .R file for family_dist_simulation is misspelled

**Comment by jbirkesteen** [comment]
I suggest the following function names:
`Testsim()` -> `sim_small()`
`family_simulation` -> `sim_fixed_family()`
`family_dist_simulaiton` -> `sim_varied_family()`
`randomized_familiy_simulation` -> `sim_random_family()`
@RasmusBrostroem, @BigMag69 and @Javert-ctrl: any thoughts?

**Comment by jbirkesteen** [comment]
Do we want to include `individualsim()` in the package? Thoughts?

**Comment by Javert-ctrl** [comment]
I think that we should keep the individualsim so that a newcomer does not get confused about the par_laib and so on.
My thought could be individualsim() -> sim_individual()

**Comment by jbirkesteen** [comment]
## We decide on the following names:
`Testsim()` -> `sim_test()`
`individualsim()` -> `sim_no_family()`
`family_simulation` -> `sim_fixed_family()`
`family_dist_simulaiton` -> `sim_varied_family()`
`randomized_familiy_simulation` -> `sim_random_family()`
This should be implemented in #30.
